--------------------------------------------------------
--  File created - Monday-April-03-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "MSAINI"."CUSTOMER" 
   (	"E_MAIL" VARCHAR2(100 BYTE), 
	"F_NAME" VARCHAR2(100 BYTE), 
	"L_NAME" VARCHAR2(100 BYTE), 
	"CUS_PHONE" VARCHAR2(15 BYTE), 
	"CUS_PASSWORD" VARCHAR2(25 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CISETS" ;
REM INSERTING into MSAINI.CUSTOMER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C00527810
--------------------------------------------------------

  CREATE UNIQUE INDEX "MSAINI"."SYS_C00527810" ON "MSAINI"."CUSTOMER" ("E_MAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CISETS" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "MSAINI"."CUSTOMER" ADD PRIMARY KEY ("E_MAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CISETS"  ENABLE;
