<option value="6.83">Aerobics</option>
<option value="5">Baseball</option>
<option value="8">Basketball</option>
<option value="8">Biking</option>
<option value="2.5">Billiards</option>
<option value="4.64">Boating</option>
<option value="3">Bowling</option>
<option value="9.5">Climbing, spelunking, caving</option>
<option value="4.5">Dancing</option>
<option value="5.33">Equestrian sports</option>
<option value="6">Fencing</option>
<option value="4.5">Fishing</option>
<option value="8">American football</option>
<option value="3.75">Golf</option>
<option value="4">Gymnastics</option>
<option value="6">Hiking</option>
<option value="8">Ice Hockey</option>
<option value="4.5">Hunting</option>
<option value="10">Martial Arts</option>
<option value="8.5">Racquet sports</option>
<option value="6">Rodeo competitions</option>
<option value="6">Rollerblading</option>
<option value="10">Rugby</option>
<option value="7.5">Running</option>
<option value="7">Skiing, ice skating, snowboarding</option>
<option value="7">Soccer</option>
<option value="5">Softball</option>
<option value="8">Cardiovascular exercise</option>
<option value="3.3">Vehicle racing</option>
<option value="5.5">Volleyball</option>
<option value="3.8">Walking</option>
<option value="5.22">Water sports</option>
<option value="3">Weightlifting/strength training</option>
<option value="6">Wrestling</option>
<option value="3">Yoga</option>